### PR TITLE
Adding EPN-TAP and ObsLocTAP to the architecture diagramme.

### PR DESCRIPTION
**Pull request by msdemlei**
I've had to shift around boxes quite a bit to make things fit.  It's
getting tight in that magic area of bespoke tabular structures (obscore,
epn-tap, obsloctap), which we've put between DM and DAL so far.  Hm...

### CODE REVIEW

**Comment by molinaro-m** [comment]
I experimented, locally, but based on ivoatex svg, and add to do the same.
Yes, the "Getting" side is *getting* crowded.

**Comment by molinaro-m** [comment]
and it will be tricky to have ProvTAP in there

**Comment by msdemlei** [comment]
> and it will be tricky to have ProvTAP in there.
I'm writing a mail to the TCG list on this.

> PS - can we have _SCS_ renamed into _ConeSearch_?

Sure.

**Comment by molinaro-m** [comment]
> > and it will be tricky to have ProvTAP in there.
> > I'm writing a mail to the TCG list on this.
> 
> > PS - can we have _SCS_ renamed into _ConeSearch_?
> 
> Sure.

Thanks!

**Pull request merged**
