### PR TITLE
Issue 28 template comentary

### PR DESCRIPTION
**Pull request by mcdittmar**
Added commentary text to the top of the workflow templates to indicate where they came from and how to install them into a new ivoatex document repository.

### CODE REVIEW

**Comment by msdemlei** [comment]
On Fri, Nov 20, 2020 at 06:24:05AM -0800, Mark Cresitello-Dittmar wrote:
> Added commentary text to the top of the workflow templates to
> indicate where they came from and how to install them into a new
> ivoatex document repository.

Quick question: Have you tried installing the workflows with this?
While I've checked YAML really has hash-initiated comments and thus
there's probably nothing that can go wrong, I'd feel a lot better if
I saw a PDF that came out of one of the updated workflow files.

**Comment by mcdittmar** [comment]
Yeah.. me too.
So, today I went through the process of installing the workflows generated from this commit into my "TransformDM" repository and getting the workflow to trigger.  I had to make a couple adjustments, but not because of the comments.
  1) I had to move them up a level cuz the 'make' adds them to the current directory (which for me is 'doc') while the workflows need to be on the base directory.
  2) the document is in a 'doc' subdirectory alongside the 'model' and 'vo-dml' subdirectories

My 'preview' workflow now runs:
   https://github.com/mcdittmar/TransformDM/releases/download/auto-pdf-preview/Transforms-draft.pdf

**Comment by mcdittmar** [comment]
I've successfully run through both workflows now.

**Comment by msdemlei** [comment]
On Fri, Nov 20, 2020 at 11:10:08AM -0800, Mark Cresitello-Dittmar wrote:
> So, today I went through the process of installing the workflows
> generated from this commit into my "TransformDM" repository and
> getting the workflow to trigger.  I had to make a couple
> adjustments, but not because of the comments.
>   1) I had to move them up a level cuz the 'make' adds them to the
>   current directory (which for me is 'doc') while the workflows
>   need to be on the base directory.

Hmyeahwell, for now I'm seriously discouraging such a layout, if only
it'll make later automatic bulk processing (where a machine checks
out all IVOA standards and does something with each one) a lot
harder.

I'd say we should *strongly* recommend organising repos such that the
ivoatex makefile is in the project root.

> My 'preview' workflow now runs:

Excellent.  Thanks.

I'm merging.

**Pull request merged**
