### PR TITLE
Adjust the formatting of URLs and DOIs.

### PR DESCRIPTION
**Pull request by nxg**
The formatting of both URLs and DOIs has been adjusted here, but more significantly, the style will now (a) handle both `doi={10.0000/abc}` and `doi={https://doi.org/10.0000/abc}` the same, and (b) if the DOI thus produced matches a URL field, then it will avoid printing both.

I also adjusted the formatting of arXiv URLs, but note that the change here presumes that all eprintid fields are referring to arXiv.

A couple of other whitespace adjustments, because I couldn't resist.

### CODE REVIEW

**Review by msdemlei — APPROVED** [review]
Thanks -- I'm happy to merge as-is, and I'm grateful that there's a test attached.  However, a regression test for ivoatex is currently maintained over in ivoatexDoc.  I'm not altogether sure how to proceed; since ivoatex is a submodule in so many other projects, I'm reluctant to move tests that may eventually use auxiliary data of non-trivial size into ivoatex proper. So... what do you think about moving something exercising your changes into ivoatexDoc/regressiontest?

**Comment by nxg** [comment]
It feels a little bit odd having tests of repository A sitting in repo B, but I'll defer to your taste here.

I see `test_all_bibliography` in `ivoatexDoc/regressiontest/run-regression.py`.  I'm sure I could do something there.

**Comment by msdemlei** [comment]
On Mon, Nov 06, 2023 at 09:54:51AM -0800, Norman Gray wrote:
> It feels a little bit odd having tests of repository A sitting in
> repo B, but I'll defer to your taste here.

Arguably.  But then as arguably you should have documentation and the
software in one repo, too.  I guess what we want is re-think the
git-modules thing and then merge the two repos.

> I see `test_all_bibliography` in
> `ivoatexDoc/regressiontest/run-regression.py`.  I'm sure I could do
> something there.

Well, it *would* be lovely if you could magick something, because,
you see, your patch does break the regression tests.  One part is
easily fixed:

  --- a/regressiontest/run-regression.py
  +++ b/regressiontest/run-regression.py
  @@ -272,8 +272,8 @@ def test_referencing():
          assert_in_file("Regress.txt",
                  'We are not talking about Plante and Stébé et al. (2010)',
                  "Bradner, S. (1997), ‘Key words",
  -               "Collections, Services Version 1.1’",
  -               "http://doi.org/10.5479/ADS/bib/2010ivoa.spec.1202P")
  +               "Collections, Services\nVersion 1.1’",
  +               "doi:10.5479/ADS/bib/2010ivoa.spec.1202P")

          execute("make bib-suggestions",
                  "2010ivoa.spec.1202P -> 2021ivoa.spec.1102D ?")


in test_referencing.  But test_all_bibliography does html, and there
DOI links now show up like this:

   doi:<a href="https://doi.org/10.5479/ADS/bib/2010ivoa.rept.1123A"/><a href="10.5479/ADS/bib/2010ivoa.rept.1123A"><tt>10.5479/ADS/bib/2010ivoa.rept.1123A</tt></a>

That won't do, and we'll have to figure out why the nesting and the
elements break.  I don't have the peace of mind right now to dig any
deeper into this; I don't remember having done anything special on
links in the bibliography in the HTML track, so I guess this needs to
be solved somewhere between the TeX markup and tthntbib.sty, the ugly
natbib stub that tth uses.

Can I termpt you with this bit of procrastination fodder?

**Comment by nxg** [comment]
Markus, hello.

> I see `test_all_bibliography` in
> `ivoatexDoc/regressiontest/run-regression.py`.  I'm sure I could do
> something there.
>
> Well, it *would* be lovely if you could magick something, because,
> you see, your patch does break the regression tests.  One part is
> easily fixed:
>
>   --- a/regressiontest/run-regression.py
>   +++ b/regressiontest/run-regression.py
>   @@ -272,8 +272,8 @@ def test_referencing():
>           assert_in_file("Regress.txt",
>                   'We are not talking about Plante and Stébé et al. (2010)',
>                   "Bradner, S. (1997), ‘Key words",
>   -               "Collections, Services Version 1.1’",
>   -               "http://doi.org/10.5479/ADS/bib/2010ivoa.spec.1202P")
>   +               "Collections, Services\nVersion 1.1’",
>   +               "doi:10.5479/ADS/bib/2010ivoa.spec.1202P")
>
>           execute("make bib-suggestions",
>                   "2010ivoa.spec.1202P -> 2021ivoa.spec.1102D ?")

I made this change, and made a rather trivial pull request (with a named branch!).  But I couldn't run the regression test.  Trying to do so produced:

```
[...]
AssertionError: 'Latexmk: All targets (Regress.pdf) are up-to-date' missing
**Failure. Dumping you in a shell in the testbed.
Exit the shell to tear it down.
```

...but when I ran 'make' in the testbed shell, I got output

```
[...]
(/usr/local/texlive/2023/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty
))) (/usr/local/texlive/2023/texmf-dist/tex/latex/natbib/natbib.sty)
(ivoatex/aas_macros.tex) (./ivoatexmeta.tex))
Latexmk: Getting log file 'Regress.log'
Latexmk: Examining 'Regress.fls'
Latexmk: Examining 'Regress.log'
Latexmk: Found input bbl file 'Regress.bbl'
Latexmk: Log file says output to 'Regress.pdf'
Latexmk: Found bibliography file(s):
  ./ivoatex/docrepo.bib
  ./ivoatex/ivoabib.bib
Latexmk: All targets () are up-to-date

```


...with empty brackets.  I don't routinely use latexmk, so I don't know why the output file is missing in the last line, even though "Log file says output to 'Regress.pdf'" is there a few lines earlier.

> in test_referencing.  But test_all_bibliography does html, and there
> DOI links now show up like this:
>
>    doi:<a href="https://doi.org/10.5479/ADS/bib/2010ivoa.rept.1123A"/><a href="10.5479/ADS/bib/2010ivoa.rept.1123A"><tt>10.5479/ADS/bib/2010ivoa.rept.1123A</tt></a>
>
> That won't do, and we'll have to figure out why the nesting and the
> elements break.  I don't have the peace of mind right now to dig any
> deeper into this; I don't remember having done anything special on
> links in the bibliography in the HTML track, so I guess this needs to
> be solved somewhere between the TeX markup and tthntbib.sty, the ugly
> natbib stub that tth uses.
>
> Can I termpt you with this bit of procrastination fodder?

You can tempt me all you like, but I'm steering clear of tth.  I did take a quick look through tthdefs.tex and the files that `grep href *` showed up, but nothing leapt out at me.

See you,

Norman



-- 
Norman Gray  :  https://nxg.me.uk

**Comment by msdemlei** [comment]
On Mon, Nov 06, 2023 at 02:25:25PM -0800, Norman Gray wrote:
> I made this change, and made a rather trivial pull request (with a named branch!).  But I couldn't run the regression test.  Trying to do so produced:
>
> ```
> [...]
> AssertionError: 'Latexmk: All targets (Regress.pdf) are up-to-date' missing
> **Failure. Dumping you in a shell in the testbed.
> Exit the shell to tear it down.
> ```
[... vs ...]
> Latexmk: All targets () are up-to-date

Oh, the joys of screen-scraping user-facing tools.  This test has
worked never failed between 2023-03-01 and, I'm sure, this afternoon
MST, when I found the HTML output problems.

No amount of reverting to previous versions of ivoatex, ivoatexDoc or
both brings back the target name.  I looked into latexmk.pl's source
as to where the targets list comes from:

   local @dests = ();
   rdb_for_some( ***@***.***, sub{ push @dests, $$Pdest if ($$Pdest); } );
   print "$My_name: All targets ***@***.***) are up-to-date\n";

Looking at rdb_for_some and trying to figure out "$$Pdest" made me
decide that perhaps I don't *need* to understand what's going on at
this point, and there's no important role this particular string
plays.

Sooo, unless you see why the latexmk output would have changed (it
must be something really stupid), I'd say let's simply change the
line in run-regressin.py to

  execute("make", " are up-to-date")

...except then the next breakage is that the generation of the role
diagram suddenly changes and you get

  '<role_diagram.pdf, id=47, 803.0pt x 602.25pt>' not in Regress.log

meaning that role diagram generation changed, too.  And again,
reverting ivoatex doesn't change this.

So... this is not something I can touch and/or fix while really
paying some basic attention the the conference here.  Something
really odd is going on here.

Let's defer the regression test. As long as the DOI HTML links in
VOUnits is ok, please just go ahead an upload it.  If they're not
easily fixable, let me back out the DOI changes in ivoatex.

Sorry about this.  These things always happen when you're travelling.

**Pull request merged**
